# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: cirrusci/flutter:3.0.5

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build a flutter version
          size: 2x
          script:
            - flutter pub get
            - flutter analyze
            - flutter test ./test
            - flutter build apk
          artifacts:
            - "build/app/outputs/bundle/release/*"
  tags:
    '*.*.*':
      - step:
          name: Build a flutter version
          size: 2x
          script:
            - flutter pub get
            - flutter analyze
            - flutter test ./test
            - flutter build apk
          artifacts:
            - "build/app/outputs/bundle/release/*"
