# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: cirrusci/flutter:stable

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build a flutter version
          runs-on:
            - self.hosted
            - linux
          size: 2x
          script:
            - flutter pub get
            - flutter test ./test
            - flutter build apk
  tags:
    '*.*.*':
      - step:
          name: Build a flutter version
          runs-on:
            - self.hosted
            - linux
          size: 2x
          script:
            - flutter pub get
            - flutter test ./test
            - flutter build apk
  custom:
    BuildAPKonRunner:
      - step:
          name: Build APK
          runs-on:
            - self.hosted
            - linux
          script:
            - flutter pub get
            - flutter test ./test
            - flutter build apk
  custom:
    BuildAPKonRunnerWithAnalyze:
      - step:
          name: Build APK
          runs-on:
            - self.hosted
            - linux
          script:
            - flutter pub get
            - flutter test ./test
            - flutter build apk
            - flutter analyze