# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: cirrusci/flutter:stable

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - gradle
            - android-sdk
          name: Build a Flutter version
          runs-on:
            - self.hosted
            - linux
          size: 2x
          script:
            - flutter pub get
            - flutter build apk --no-tree-shake-icons
          artifacts:
            - build/app/outputs/flutter-apk/*.apk

  tags:
    '*.*.*':
      - step:
          name: Build a Flutter version
          runs-on:
            - self.hosted
            - linux
          size: 2x
          script:
            - flutter pub get
            - flutter build apk --no-tree-shake-icons
          artifacts:
            - build/app/outputs/flutter-apk/*.apk

  custom:
    BuildAPKonRunner:
      - step:
          caches:
            - gradle
            - android-sdk
          name: Build APK
          runs-on:
            - self.hosted
            - linux
          script:
            - flutter pub get
            - flutter build apk --no-tree-shake-icons
          artifacts:
            - build/app/outputs/flutter-apk/*.apk

    BuildAPKonBitbucket:
      - step:
          name: Build APK
          script:
            - flutter pub get
            - flutter build apk --no-tree-shake-icons
          artifacts:
            - build/app/outputs/flutter-apk/*.apk

definitions:
  caches:
    android-sdk: android-sdk

